const initialState = {
  isLoggedIn: false,
  loggedInUser: '',
  signUpInputUsername: '',
  signUpInputPassword: '',
  signUpInputEmail: '',
  loginInputEmail: '',
  loginInputPassword: '',
  signUpError: false,
  signUpErrorMsg: '',
  loginError: false,
  loginErrorMsg: '',
  passwordErrorMsg: '',
  usernameErrorMsg: '',
  emailErrorMsg: '',
  forgotInputEmail: '',
  emailStatusMsg: '',
  emailSuccess: false,
};

